"use strict";

// Single source of truth for enums shared by models, validators and the frontend.
const ROLES = { ADMIN: "ADMIN", AGENT: "AGENT", CUSTOMER: "CUSTOMER" };

const TICKET_STATUS = {
  OPEN: "OPEN",
  IN_PROGRESS: "IN_PROGRESS",
  WAITING_CUSTOMER: "WAITING_CUSTOMER",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED",
};

const TICKET_PRIORITY = { LOW: "LOW", MEDIUM: "MEDIUM", HIGH: "HIGH", URGENT: "URGENT" };

const CONVERSATION_STATUS = {
  ACTIVE: "ACTIVE",
  WAITING_AGENT: "WAITING_AGENT",
  WITH_AGENT: "WITH_AGENT",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED",
};

const SENDER_TYPE = { CUSTOMER: "CUSTOMER", AI: "AI", AGENT: "AGENT", SYSTEM: "SYSTEM" };

const MESSAGE_TYPE = { TEXT: "TEXT", TOOL_RESULT: "TOOL_RESULT", HANDOFF: "HANDOFF", NOTE: "NOTE" };

const ORDER_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  PROCESSING: "PROCESSING",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  REFUNDED: "REFUNDED",
};

const DOCUMENT_STATUS = { PROCESSING: "PROCESSING", READY: "READY", FAILED: "FAILED" };

module.exports = {
  ROLES,
  TICKET_STATUS,
  TICKET_PRIORITY,
  CONVERSATION_STATUS,
  SENDER_TYPE,
  MESSAGE_TYPE,
  ORDER_STATUS,
  DOCUMENT_STATUS,
};
